export const CATEGORIES_ACTION_TYPES={
    
    FETCH_CATEGORIES_START:'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCSS:'FETCH_CATEGORIES_SUCCSS',
    FETCH_CATEGORIES_FAILED:'FETCH_CATEGORIES_FAILED',
}